apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: fastcommerce-secrets
  namespace: fastcommerce

data:
  # All values must be base64 encoded
  POSTGRES_USER: ZmFzdHVzZXI=
  POSTGRES_PASSWORD: ZmFzdHBhc3M=
  SECRET_KEY: ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
