apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: fastcommerce
spec:
  # LoadBalancer: provisions an external load balancer.
  # On cloud providers, this creates an actual cloud load balancer.
  # On minikube with tunnel running, this assigns 127.0.0.1 as EXTERNAL-IP.
  type: LoadBalancer
  selector:
    app: fastcommerce-api
  ports:
    - port: 80 # external port (what Locust and curl talk to)
      targetPort: 8000 # pod port (what Gunicorn listens on)
